<?php $this->layout('layouts/admin'); ?>

<?php $this->section('content') ?>
    <ol class="breadcrumb">
        <li><a href="/admin"><?= $this->translate('admin_link') ?></a></li>
        <li><a href="/admin"><?= $this->translate('tags_link') ?></a></li>
        <li class="active"><?= $this->translate('create_tag') ?></li>
    </ol>

    <form method="post" action="/admin/tags">
        <div class="form-group">
            <label for="name"><?= $this->translate('common_name') ?></label>
            <input type="text" value="<?= @$this->params['name'] ?>" class="form-control" name="name" id="name" placeholder="Name">
        </div>

        <div class="form-group">
            <label for="name"><?= $this->translate('common_visibility') ?></label>
            <select name="public" class="form-control">
                <option value="1"><?= $this->translate('option_public') ?></option>
                <option value="0"><?= $this->translate('option_private') ?></option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
        <a href="/admin/tags" class="btn btn-default">Cancel</a>
    </form>
<?php $this->replace() ?>
